# https://github.com/JunkFood02/Seal/blob/main/.github/workflows/android.yml

name: Build Release APK

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v3

      - run: gradle assembleRelease

      - name: Sign app APKs
        id: sign_app
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          APK_FILE=$(find . -type f -name "*-signed.apk")
          if [ -n "$APK_FILE" ]; then
            mv "$APK_FILE" "$(dirname "$APK_FILE")/app-signed.apk"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-signed
          path: app/build/outputs/apk/release/app-signed.apk
          if-no-files-found: error
          retention-days: 20